[workspace]
members = ["x402"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["JamiiDao Developers <support@jamiidao.app>"]
edition = "2024"
license = "Apache-2.0 OR CC0-1.0"


[workspace.dependencies]
rusty-x402 = { path = "./x402" }
